### ISSUE TITLE
taglib version

### ISSUE THREAD

**Issue by c--w** [schneefux/node-taglib3#2]
You are using taglib master while branch taglib2 is the one you should be using. 
In CMakeLists.txt you should put 
set(REVISION "65a6a4e225fff1288148de92721418e1c634713b")
instead of 
set(REVISION "v1.11.1")

Branch taglib 2 is more advanced with more features. For example it supports pictures tag for obtaining album art that is often part of the song file..

**Comment by schneefux** [comment]
Thank you!
